CI: use fresh config.yml for build
Since d3b8408cb8 fdroiddata has a config.yml. Override this in CI fix:

  File "/usr/lib/python3/dist-packages/ruamel/yaml/constructor.py", line 294, in check_mapping_key
9726
    raise DuplicateKeyError(*args)
9727
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
9728
  in "config.yml", line 3, column 1
9729
found duplicate key "repo_keyalias" with value "sova" (original value: "ciarang")
9730
  in "config.yml", line 62, column 1