Fennec F-Droid: add a potential build failure fix
Try ./mach build three times as a workaround for the following error:

    error: failed to get `jsparagus` as a dependency of package `smoosh v0.1.0 (/home/vagrant/build/srclib/MozFennec/js/src/frontend/smoosh)`
    Caused by:
      failed to load source for dependency `jsparagus`
    Caused by:
      Unable to update https://github.com/mozilla-spidermonkey/jsparagus?rev=20d01b2c01a5be01d3dea3ec7a1ede2fdda3d9d2
    Caused by:
      failed to clone into: /home/vagrant/.cargo/git/db/jsparagus-00a7b91db6b71f62
    Caused by:
      attempting to update a git repository, but --frozen was specified
    gmake[3]: *** [backend.mk:115: config/.deps/cbindgen-metadata.json.stub] Error 101